### PR TITLE
Portable win32 binaries

### LINKED ISSUE #587: Windows portable version
I would suggest making a portable version for Windows. From what I understand Museeks AppImage for Linux holds the default AppImage ruleset and hence is automaticaly portable. For macOS one cannot really make a portable app. For Windows you certainly can and programs are supported with this release format.

### PR DESCRIPTION
**Pull request by martpie**
- Fixes #587
- Fixes ia32 windows binaries not created (🙈)

### CODE REVIEW

**Comment by vivadavid** [comment]
Hi,

With the new changes introduced in 0.20.0, I can't see any more the portable version for Windows.

Will it be available in the future?

Thanks!

**Comment by martpie** [comment]
@vivadavid yeaah, we kind of need an installer now because we need to ensure Webview2 is installed before running the app (which explains the 20x binary size reduction).

I will investigate though, on how to recreate portable binaries, but I don't think it will be easy.

**Comment by vivadavid** [comment]
> @vivadavid yeaah, we kind of need an installer now because we need to ensure Webview2 is installed before running the app (which explains the 20x binary size reduction).
> 
> I will investigate though, on how to recreate portable binaries, but I don't think it will be easy.

If it's a big deal, it doesn't matter: I'm just using the installer. However, in the long term, it'd be useful to have a portable version.

Thanks for your quick reply.

**Comment by martpie** [comment]
Can you explain more in detail why a portable version is more desirable than a classic installer? 

Is it just the ease of use? A lack of admin right? Something else?

**Comment by vivadavid** [comment]
In my particular case, when I learn about new software and I want to test it to know if it's of any use to me, I prefer not to write anything into the registry. Also, certain uninstallers don't work perfectly well and you end up keeping undesired files on your computer.

There's another case scenario. If I have, for example, Subtitle Edit in portable version, I can download all the Whisper models that I need and keep them all in the same folder. If, later on, I need to format my PC and have a fresh Windows install, I don't have to install the programme againt, go through all the settings, download the Whisper models, download Tesseract, etc.

In the case of a music player, I guess that, the first time your music folder is scanned, a library is generated, possibly even with a list of all your covers. It's a clean solution to have both the programme and the music library in the same folder, so that, if you format your PC, you don't have create your library from scratch again.

**Pull request merged**
