### PR TITLE
Update webm in supported extensions

### PR DESCRIPTION
**Pull request by HaiDang666**

### CODE REVIEW

**Comment by martpie** [comment]
Have you tried it and confirm it worked when importing webm files to your library?

**Comment by HaiDang666** [comment]
yes, museeks can load and play my webm files

Screen Shot 2021-06-15 at 16 51 35

**Comment by martpie** [comment]
It seems there is an issue with CI env vars for external PRs, it's weird 😄 

Thank you very much for the PR!

**Comment by HaiDang666** [comment]
thank you, I'm glad to help.

**Pull request merged**
