### PR TITLE
Replace "macos" with "app-close" plugin

### PR DESCRIPTION
**Pull request by uklotzde**
Fixes the build on Linux (and probably Windows).

### CODE REVIEW

**Comment by martpie** [comment]
Due to force-pushes, I think there are conflicts here. Could you maybe just rebase on top `tauri` and ignore [aa1b762](https://github.com/martpie/museeks/pull/750/commits/aa1b7627f7e80e7c43d4d5c46ba7eabb38d340e0) ?

Sorry, that's due to me using Sapling SCM for managing my work, and it does not work well in a collaborative environment with GitHub.

**Comment by martpie** [comment]
Due to force-pushes, I think there are conflicts here. Could you maybe just rebase on top `tauri` and ignore [aa1b762](https://github.com/martpie/museeks/pull/750/commits/aa1b7627f7e80e7c43d4d5c46ba7eabb38d340e0) ?

Sorry, that's due to me using Sapling SCM for managing my work, and it does not work well in a collaborative environment with GitHub.

**Comment by uklotzde** [comment]
> Sorry, that's due to me using Sapling SCM for managing my work, and it does not work well in a collaborative environment with GitHub.

Then GitHub is probably the wrong platform for collaboration? I also noticed the weird structure of this repo.

**Comment by martpie** [comment]
Great job, thank you for that!

> Then GitHub is probably the wrong platform for collaboration

Yesn't. GitHub is working fine, it's just I was working alone on the Tauri port, so I just was using my own sauce and experimenting with [`sapling`](https://sapling-scm.com/).

Now we have a Dev branch named `tauri`, I can still make messes in my own side-branches, and we can consider the `tauri` branch "stable" (more or less), or at least, "the one we should merge other branches into". 

> I also noticed the weird structure of this repo.

is it haha?

**Comment by uklotzde** [comment]
> is it haha?

At least in `git gui` the branch structures look confusing. Unhandy if you want to quickly browse the recent history.

**Comment by martpie** [comment]
Right, let me clean up a few branches ;) the `pr-xxx` come from Sapling, as Sapling considers branches an implementation details, and only the commit messages are important.

**Pull request merged**
