### PR TITLE
Update metadata from native parser

### PR DESCRIPTION
**Pull request by HaiDang666**
I found that some metadata do not sit in `common` but in `native` from `music-metadata` package.

Screen Shot 2021-06-17 at 16 46 38

Before:
Screen Shot 2021-06-18 at 13 26 43

After:
Screen Shot 2021-06-18 at 13 02 04

### CODE REVIEW

**Comment by martpie** [comment]
Can you send me some of those files per email so I can test them myself?

**Comment by HaiDang666** [comment]
> Can you send me some of those files per email so I can test them myself?

sure but do we have a discorg server for this project ?

**Comment by martpie** [comment]
We used to have a Gitter, but maybe a Discord could be a good idea indeed.

Thanks for the files!

**Comment by HaiDang666** [comment]
Thank. It will be convenient to communicate.

**Comment by HaiDang666** [comment]
should I close this since the metadata package has done it?

**Pull request closed without merging**
