### PR TITLE
Fixing empty playlist on context menu create

### PR DESCRIPTION
**Pull request by MrDoctorKovacic**
#494 

Enjoy your weekend!

### CODE REVIEW

**Comment by martpie** [comment]
You create a playlist, but not adding any files in it anymore, which breaks the feature 😄 

The problem is probably coming from somewhere else, I'll investigate

**Comment by MrDoctorKovacic** [comment]
Thanks for looking, but are you sure? This worked when I tested it.

Another option is to manually refresh after the original 2 lines

**Comment by martpie** [comment]
Ah wait, I may have missed sth

**Comment by martpie** [comment]
you are actually absolutely right

**Pull request merged**
